### ISSUE TITLE
Unhandled exception occurs when parsing code that calls `include` at the top level

### ISSUE THREAD

**Issue by sinsoku** [soutaro/rbs-inline#105]
## Steps to reproduce

Parse Ruby files that call `include` at the top level like this:

```ruby
# rbs_inline: enabled
module M
end
include M
```

## Expected behavior
No error occurs.

## Actual behavior
Exits with an error as below.

```console
$ rbs-inline issue.rb
/Users/sinsoku/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-inline-0.8.0/lib/rbs/inline/parser.rb:123:in `current_class_module_decl!': unhandled exception
	from /Users/sinsoku/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rbs-inline-0.8.0/lib/rbs/inline/parser.rb:285:in `visit_call_node'
	from /Users/sinsoku/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.0.0/lib/prism/node.rb:2222:in `accept'
	from /Users/sinsoku/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.0.0/lib/prism/visitor.rb:31:in `block in visit_child_nodes'
	from /Users/sinsoku/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.0.0/lib/prism/visitor.rb:31:in `each'
	from /Users/sinsoku/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.0.0/lib/prism/visitor.rb:31:in `visit_child_nodes'
	from /Users/sinsoku/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.0.0/lib/prism/node.rb:15198:in `accept'
	from /Users/sinsoku/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.0.0/lib/prism/visitor.rb:31:in `block in visit_child_nodes'
	from /Users/sinsoku/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/prism-1.0.0/lib/prism/visitor.rb:31:in `each'
```

## Notes

I found this error by trying `rbs-inline --opt-out` on a Redmine repository.

refs: https://github.com/redmine/redmine/blob/5.1.3/lib/plugins/gravatar/spec/gravatar_spec.rb

**Comment by soutaro** [comment]
Fixed in #70
